package context

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mskasa/kizami/internal/decision"
)

// summaryCellMaxLen bounds a manifest row's Decision cell so a single verbose ADR can't
// balloon the whole manifest's token cost: docs/decisions/2026-08-03-agent-manifest-sync-format.md
const summaryCellMaxLen = 160

// manifestStartMarker and manifestEndMarker delimit the block kizami owns inside a target
// file (e.g. CLAUDE.md, AGENTS.md). Sync replaces everything between them in place, or
// appends the whole block if the markers aren't found:
// docs/decisions/2026-08-03-agent-manifest-sync-format.md
const (
	manifestStartMarker = "<!-- kizami:start -->"
	manifestEndMarker   = "<!-- kizami:end -->"
)

// ManifestEntry is one row of the agent manifest: a decision and the files it governs.
type ManifestEntry struct {
	Slug         string
	RelatedFiles []string
	Decision     string
}

// Manifest returns one ManifestEntry per governing decision (Active or Superseded) across
// dirs, sorted by slug. Decisions with an empty Related Files section are skipped — they
// have nothing to point an agent at.
func Manifest(dirs []string) ([]*ManifestEntry, error) {
	docs, err := collectGoverningDocs(dirs)
	if err != nil {
		return nil, err
	}

	var entries []*ManifestEntry
	for _, d := range docs {
		related, err := decision.ParseRelatedFiles(d.File)
		if err != nil {
			return nil, fmt.Errorf("parsing related files for %s: %w", d.File, err)
		}
		if len(related) == 0 {
			continue
		}

		summary, err := summaryText(d.File, false)
		if err != nil {
			return nil, fmt.Errorf("reading summary for %s: %w", d.File, err)
		}

		entries = append(entries, &ManifestEntry{
			Slug:         d.Slug,
			RelatedFiles: related,
			Decision:     summary,
		})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Slug < entries[j].Slug
	})
	return entries, nil
}

// RenderManifest renders entries as the full marker-delimited block to place in a target file.
func RenderManifest(entries []*ManifestEntry) string {
	var sb strings.Builder
	sb.WriteString(manifestStartMarker + "\n")
	sb.WriteString("<!-- Generated by `kizami agents sync` — do not edit by hand. -->\n")
	sb.WriteString("## Decisions Governing This Codebase\n\n")
	sb.WriteString("This repository's design decisions are recorded in `docs/decisions/` (and `docs/design/`). ")
	sb.WriteString("Read the decision below before editing files it covers.\n\n")

	if len(entries) == 0 {
		sb.WriteString("_No governing decisions found._\n")
	} else {
		sb.WriteString("| Related Files | Decision | Slug |\n")
		sb.WriteString("|---|---|---|\n")
		for _, e := range entries {
			sb.WriteString("| ")
			sb.WriteString(tableCell(joinRelatedFiles(e.RelatedFiles), 0))
			sb.WriteString(" | ")
			sb.WriteString(tableCell(e.Decision, summaryCellMaxLen))
			sb.WriteString(" | ")
			sb.WriteString(e.Slug)
			sb.WriteString(" |\n")
		}
	}

	sb.WriteString("\nFull text: `kizami show <slug>` · Reverse lookup from changed files: `kizami context <files...>`\n")
	sb.WriteString(manifestEndMarker)
	return sb.String()
}

func joinRelatedFiles(entries []string) string {
	quoted := make([]string, len(entries))
	for i, e := range entries {
		quoted[i] = "`" + e + "`"
	}
	return strings.Join(quoted, ", ")
}

// tableCell collapses text to a single line (safe for a Markdown table cell) and truncates
// it to maxLen characters, appending "…" if it was cut. maxLen <= 0 means no truncation.
func tableCell(text string, maxLen int) string {
	text = strings.Join(strings.Fields(text), " ")
	text = strings.ReplaceAll(text, "|", `\|`)
	if maxLen > 0 {
		// Truncate by rune count, not byte count — slicing a string by byte index can
		// split a multi-byte UTF-8 rune (e.g. Japanese) and produce invalid UTF-8.
		if runes := []rune(text); len(runes) > maxLen {
			text = strings.TrimSpace(string(runes[:maxLen])) + "…"
		}
	}
	return text
}
